//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DisReqs = new HashSet<DisReq>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public int AreaId { get; set; }
        public int UserId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<DisReq> DisReqs { get; set; }
        public virtual User User { get; set; }
    }
}
