//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqDetail
    {
        public int Id { get; set; }
        public string FoodName { get; set; }
        public int ReqId { get; set; }
    
        public virtual DisReq DisReq { get; set; }
    }
}
